### ISSUE TITLE
Incorrect Documentation about source of Error

### ISSUE THREAD

**Issue by MattBialas** [nasa/cumulus#1064]
https://github.com/nasa/cumulus/blob/3b07b1c0fba29be8d860041959f5d5deeb03f454/docs/system-documentation/system-documentation.md

The section at the bottom: **Error: Unable to import module 'index': Error**

And the solution: "In order to resolve this issue, update the lambda source (in lambdas.yml, to point to the parent directory of the index.js file."

This is not correct. Add **any** syntax error **inside** your index.js file, and CloudWatch Logs will report this error. The error means that it is unable to import the module [because of some error].

It is not an error referencing the file.

When I expand the section in AWS Step Functions, it reveals the real error with my index.js file:

```
"cause": {
    "errorMessage": "Cannot find module 'node_modules/@cumulus/cumulus-message-adapter-js'",
```

But clicking the button in the Step Function console that says "CloudWatch Logs" just shows me the generic:

`Unable to import module 'index': Error`

**Comment by markdboyd** [comment]
@MattBialas You're right that the error is more generic than the case noted in our docs. I think the docs are only trying to capture the most common error causes which is why we mentioned that one.

In your case, I think you may need to add `useMessageAdapter: true` in your `lambdas.yml` file where you are defining this Lambda. It looks like our docs may not be stating that anywhere, which I will address

**Comment by MattBialas** [comment]
Thanks Mark. Once I realized the issue was related to the message adapter, I was able to proceed from there.

I was held up for a *long* time thinking there was an issue simply trying to reference the file.

**Comment by markdboyd** [comment]
@MattBialas Yeah, I updated the docs to address that there may be other causes of that error, including the message adapter issue. I also updated the docs to more clearly identify when the message adapter is needed.
