### ISSUE TITLE
EBS support in ECS

### ISSUE THREAD

**Issue by garysieling** [nasa/cumulus#1095]
The ECS settings support adding additional EBS storage, but never mount it to the EC2 images.

**Comment by markdboyd** [comment]
@garysieling This issue seems to be a remnant from when Cumulus was deployed via Kes. Cumulus is now deployed via Terraform. I'm not sure if this issue was resolved in our deployment code, but since our deployment tooling has completely changed, I'm going to close. Feel free to re-open if you need further assistance
